name: veracity
favicon: null
layout_spectrum: 0.014570249477401376
typography_spectrum: 0.2699809027835727
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.23448838479816914
  lightness: 0.7614287841133773
  saturation: 0.3756222769152373
  rhythmicContrast: 0.7402543865609914
purpose: []
